//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectASP.Net.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CShirt
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string Category { get; set; }
        public string Color { get; set; }
        public Nullable<double> UnitPrice { get; set; }
        public string ImageUrl { get; set; }
    }
}
