//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectASP.Net.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class Product
    {
        public Product()
        {
            this.ProductDetails = new HashSet<ProductDetail>();
        }
    
        public int Id { get; set; }
       [Required (ErrorMessage="Name Required")]
        public string ProductName { get; set; }
        [Required(ErrorMessage = "Category Required")]
        public string ProductCategory { get; set; }
        [Required(ErrorMessage = "Price Required")]
        public double ProductPrice { get; set; }
        public int ProductQuantity { get; set; }
        public string ImageUrl { get; set; }
        public string Detail { get; set; }
    
        public virtual ICollection<ProductDetail> ProductDetails { get; set; }
    }
}
